server.port=8081
spring.application.name=event-notificator
spring.datasource.url=jdbc:postgresql://localhost:5433/event-notificator-db
spring.datasource.username=event-notificator-db
spring.datasource.password=event-notificator-db
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
jwt.secretKey = bXlTdXBlclNlY3JldEtleUZvckpXVDEyMzQ1Njc4OTA=
scheduler.cron: 0 0 0 * * MON