server.port=8080
spring.application.name=event-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/event-manager-db
spring.datasource.username=event-manager-db
spring.datasource.password=event-manager-db
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=public
spring.flyway.default-schema=public
springdoc.swagger-ui.url: /openapi.yaml


jwt.lifetime = 86400000
jwt.secretKey = bXlTdXBlclNlY3JldEtleUZvckpXVDEyMzQ1Njc4OTA=
scheduler.cron = 0 * * * * *